name: build-pytorch-docs

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows for the workflow to be manually started through the GitHub UI
  workflow_dispatch:

jobs:
  build-pytorch-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, windows-latest ]
    # runs-on: ubuntu-latest
    steps:
      - name: Check Contexts and Secrets
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "runner.os = ${{ runner.os }}"
          echo "[Secrets]"
          echo "secrets.GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install Apt Packages
        run: |
          # sudo apt install libstdc++6
          apt list libstdc++6
          #
          strings /usr/share/miniconda/lib/libstdc++.so.6 | grep ‘GLIBCXX_3’

      # - name: Install Conda
      #   uses: s-weigand/setup-conda@v1
      
      # - name: Check Conda Version and Packages
      #   run: |
      #     echo "----------------------------------------"
      #     conda --version
      #     echo "----------------------------------------"
      #     conda list
      #     echo "----------------------------------------"

      # - name: Clone the PyTorch Repository
      #   run: |
      #     git clone --recursive --depth=1 --branch=main https://github.com/pytorch/pytorch.git pytorch

      # - name: Install the Requirements
      #   run: |
      #     cd pytorch
      #     conda install cmake ninja
      #     pip install -r requirements.txt
      #     cd docs
      #     pip install -r requirements.txt

      # - name: Install the PyTorch (for non-Windows)
      #   if: runner.os != 'Windows'
      #   run: |
      #     # export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
      #     export _GLIBCXX_USE_CXX11_ABI=1
      #     cd pytorch
      #     python setup.py develop

      # - name: Build PyTorch Documentation
      #   run: |
      #     cd pytorch
      #     cd docs
      #     make html

      # - name: Deploy to 'gh-pages' branch
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
      #     folder: ./pytorch/docs/build/html
      #     target-folder: .
      #     clean: false
